# This is the name of the workflow.
name: Deploy

#This is the event that triggers the workflow. In this case, the workflow is triggered when a push event occurs on the main branch or when a pull request is opened or updated.
on:
  push:
    branches: 
      - main
  pull_request:
    branches: 
      - main

  
#This is the job that the workflow runs. The job is named ci.
    jobs:
    #This job runs on the latest version of the Ubuntu operating system.
    ci:
      name: Deploy
      runs-on: ubuntu-latest

      #This is the list of steps that the job runs.
      steps:
        #This step checks out the code from the repository.
        - uses: actions/checkout@v3

        #This step uses the setup-node action to set up Node.js.ß
        - name: Deploy
          if: github.ref == 'refs/heads/main'
          env:
            DEPLOY_URL: ${{ secrets.https://api.render.com/deploy/srv-ctbp4oggph6c73a5trhg?key=1ww6xbHbtLEURL }}
          run: |
            curl "$DEPLOY_URL"